// Auto-generated from api/pkg/constants/constants.go
// DO NOT EDIT MANUALLY - Changes will be overwritten
// Generated by: api/scripts/generate-ts-constants.go

// =============================================================================
// SHARED GRID CONSTANTS
// =============================================================================
export const BOARD_SIZE = 9
export const SUBGRID_SIZE = 3
export const TOTAL_CELLS = 81
export const MIN_GIVENS = 17
export const MAX_SOLVER_NODES = 10000000
export const TIER_SIMPLE = "simple"
export const TIER_MEDIUM = "medium"
export const TIER_HARD = "hard"
export const TIER_EXTREME = "extreme"
export const ACTION_ASSIGN = "assign"
export const ACTION_ELIMINATE = "eliminate"
export const ACTION_CONTRADICTION = "contradiction"
export const ACTION_CANDIDATE = "candidate"
export const ACTION_FIX_ERROR = "fix-error"
export const ACTION_STALLED = "stalled"
export const ACTION_ERROR = "error"
export const ACTION_DIAGNOSTIC = "diagnostic"
export const ACTION_UNPINPOINTABLE_ERR = "unpinpointable-error"
export const STATUS_COMPLETED = "completed"
export const STATUS_STALLED = "stalled"
export const STATUS_MAX_STEPS_REACHED = "max_steps_reached"
